OPENFDA_API_KEY = "xSpH1wJPYgwaTxla835Hrf20Rl2KragoNLN0jHqj"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/XXX/YYY/ZZZ"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 465
EMAIL_USER = "kevinepaladin@gmail.com"   # the sender
EMAIL_PASS = "your_16_char_app_password"
EMAIL_TO   = "kevinepaladin@gmail.com"   # the recipient (can be same)
